language: objective-c
osx_image: xcode7.2

script: set -o pipefail && xcodebuild -destination "OS=9.2,name=iPad Air 2" -scheme "RxSugar-iOS" -project "RxSugar.xcodeproj" build test | second_curtain | xcpretty --color --test
